/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        navy: {
          950: '#050d20',
          900: '#07102a',
          800: '#0d1b3e',
          700: '#1a2d5a',
          600: '#243a72',
          500: '#2e4a8f',
        },
        brand: {
          50:  '#eff6ff',
          100: '#dbeeff',
          200: '#b8ddff',
          300: '#7cc3ff',
          400: '#5aabff',
          500: '#2d8ef5',
          600: '#1a74d4',
          700: '#155cab',
          800: '#1a4a80',
        },
      },
      fontFamily: {
        display: ['Syne', 'sans-serif'],
        body:    ['Plus Jakarta Sans', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      backgroundImage: {
        'gradient-brand': 'linear-gradient(135deg, #2d8ef5 0%, #1a2d5a 100%)',
        'gradient-hero':  'linear-gradient(160deg, #050d20 0%, #0d1b3e 50%, #070e25 100%)',
        'gradient-card':  'linear-gradient(145deg, rgba(13,27,62,0.9), rgba(7,16,42,0.95))',
        'gradient-glow':  'radial-gradient(ellipse at center, rgba(45,142,245,0.15) 0%, transparent 70%)',
      },
      animation: {
        'float':       'float 4s ease-in-out infinite',
        'float-slow':  'float 7s ease-in-out infinite',
        'pulse-ring':  'pulseRing 2s ease-out infinite',
        'spin-slow':   'spin 20s linear infinite',
        'fade-up':     'fadeUp 0.7s ease both',
        'slide-in':    'slideIn 0.6s ease both',
        'shimmer':     'shimmer 2s linear infinite',
        'blink':       'blink 2s ease-in-out infinite',
        'gradient':    'gradientShift 4s ease infinite',
        'count-up':    'countUp 0.6s ease both',
        'bounce-x':    'bounceX 1.5s ease-in-out infinite',
        'draw':        'draw 2s ease forwards',
      },
      keyframes: {
        float:         { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-14px)' } },
        pulseRing:     { '0%': { transform: 'scale(0.85)', opacity: 1 }, '100%': { transform: 'scale(2)', opacity: 0 } },
        fadeUp:        { from: { opacity: 0, transform: 'translateY(32px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideIn:       { from: { opacity: 0, transform: 'translateX(-24px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        shimmer:       { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        blink:         { '0%,100%': { opacity: 1 }, '50%': { opacity: 0.3 } },
        gradientShift: { '0%,100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        countUp:       { from: { opacity: 0, transform: 'translateY(20px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        bounceX:       { '0%,100%': { transform: 'translateX(0)' }, '50%': { transform: 'translateX(6px)' } },
        draw:          { from: { strokeDashoffset: 1000 }, to: { strokeDashoffset: 0 } },
      },
      boxShadow: {
        'brand':    '0 0 40px rgba(45,142,245,0.25)',
        'brand-sm': '0 0 20px rgba(45,142,245,0.18)',
        'brand-lg': '0 0 80px rgba(45,142,245,0.30)',
        'card':     '0 8px 40px rgba(0,0,0,0.4)',
        'card-hover': '0 16px 60px rgba(45,142,245,0.20)',
      },
    },
  },
  plugins: [],
}
