// ── Case Studies Data ─────────────────────────────────────────────────────
export const CASE_STUDIES = [
  {
    id: 'shopify-uploader',
    icon: '🛍️',
    tag: 'E-Commerce',
    title: 'Shopify Product Uploader',
    subtitle: 'Eliminating 12 hours of weekly manual data entry for an e-commerce brand',
    desc: 'Automated bulk product uploads to Shopify with zero manual entry — client saved 12 hours per week and eliminated data errors entirely.',
    result: '12 hrs/week saved',
    tools: ['Make', 'Notion', 'Shopify API'],
    color: '#2d8ef5',
    image: null,
    client: 'E-Commerce Brand',
    duration: '2 weeks',
    // Full narrative
    challenge: `The client ran a fast-growing Shopify store with over 500 SKUs being added monthly. Their team was spending 12+ hours every week manually copying product data from a Notion database into Shopify — title, description, pricing, variants, images, and SEO fields — one by one. The process was error-prone, with frequent mismatch between the Notion source of truth and the live store.`,
    solution: `We designed an automated pipeline using Make (formerly Integromat) that watches the Notion products database for new entries or status changes. When a product is marked "Ready to Publish" in Notion, Make triggers a multi-step workflow that: formats the data to Shopify's API schema, handles variant generation, uploads images via CDN URLs, creates the product in draft mode, then marks the Notion record as "Live" with the Shopify product ID for reference.`,
    outcome: `The client now publishes products in seconds instead of minutes. The weekly 12-hour manual task has been fully eliminated. Data accuracy improved to near 100% since the automation reads directly from the authoritative Notion database. The team redirected those saved hours to customer acquisition and merchandising.`,
    metrics: [
      { label: 'Time Saved', value: '12 hrs/wk' },
      { label: 'Error Rate', value: '~0%' },
      { label: 'Products/Month', value: '500+' },
      { label: 'ROI', value: '20× in month 1' },
    ],
    process: [
      'Audited existing Notion database schema and Shopify product structure',
      'Mapped all fields including variants, images, and SEO metadata',
      'Built Make scenario with error handling and retry logic',
      'Added Slack notification on success or failure',
      'Tested with 50 products before full rollout',
      'Trained team on the new "Ready to Publish" workflow trigger',
    ],
  },
  {
    id: 'meeting-summary',
    icon: '🗒️',
    tag: 'Notion Integration',
    title: 'AI Meeting Summary → Notion',
    subtitle: 'Never lose a meeting insight again — AI-powered notes, auto-filed in Notion',
    desc: 'AI-generated meeting summaries pushed automatically into a structured Notion database with tagged action items and owner assignments.',
    result: '100% capture rate',
    tools: ['n8n', 'OpenAI', 'Notion'],
    color: '#5aabff',
    image: null,
    client: 'SaaS Startup',
    duration: '1 week',
    challenge: `The client held 8–12 internal and client meetings per week. Notes were scattered across Google Docs, Slack threads, and personal notepads. Action items were frequently missed, follow-ups fell through the cracks, and there was no searchable record of what was discussed or decided in past meetings.`,
    solution: `We built an n8n automation that receives meeting transcripts (via Fireflies.ai or manual upload), sends them to OpenAI with a structured prompt to extract: summary, key decisions, action items with owners and due dates, and sentiment. The structured output is then parsed and pushed into a Notion database where each meeting becomes a linked record connected to the relevant project, client, and team member pages.`,
    outcome: `100% of meetings are now captured and searchable. Action items are automatically assigned in Notion with due dates. The team reduced follow-up emails by 60% and onboarding new team members became significantly easier since the entire decision history is documented and searchable.`,
    metrics: [
      { label: 'Capture Rate', value: '100%' },
      { label: 'Meetings/Week', value: '10+' },
      { label: 'Follow-up Emails', value: '−60%' },
      { label: 'Setup Time', value: '1 week' },
    ],
    process: [
      'Integrated meeting transcript source (Fireflies.ai webhook)',
      'Designed OpenAI prompt for structured JSON extraction',
      'Built Notion database schema for meetings, decisions, action items',
      'Created n8n workflow with conditional logic per meeting type',
      'Added daily digest Slack message with pending action items',
      'Trained team on the new meeting workflow',
    ],
  },
  {
    id: 'video-pipeline',
    icon: '🎬',
    tag: 'AI Automation',
    title: 'AI Video Generation Pipeline',
    subtitle: '5× content output from a single brief — fully automated video production',
    desc: 'Fully automated AI video creation from a single content brief — 5× content output with consistent brand voice across all platforms.',
    result: '5× content output',
    tools: ['Make', 'OpenAI', 'Heygen'],
    color: '#2d8ef5',
    image: null,
    client: 'Content Creator',
    duration: '3 weeks',
    challenge: `A content creator and marketing consultant was spending 4–6 hours per video — scripting, recording, editing, captioning, and resizing for different platforms. They could only produce 2–3 videos per week, far below what the algorithm rewards. They needed to scale without hiring a full production team.`,
    solution: `We built a Make pipeline where the client submits a single content brief (topic, tone, key points) into Notion. From there: OpenAI generates a full script and hooks for each platform, Heygen renders an AI avatar video from the script, the video is auto-captioned, resized for TikTok/Reels/YouTube Shorts, and uploaded to a Notion content calendar with publishing metadata ready for each platform.`,
    outcome: `Output scaled from 2–3 videos per week to 12–15. The client's follower growth accelerated 3× and brand sponsorship enquiries doubled within 2 months. Total production time per piece dropped from 5 hours to under 20 minutes of human review.`,
    metrics: [
      { label: 'Videos/Week', value: '2→12+' },
      { label: 'Prod. Time', value: '5hr→20min' },
      { label: 'Follower Growth', value: '3× faster' },
      { label: 'Content Backlog', value: 'Eliminated' },
    ],
    process: [
      'Designed content brief template in Notion',
      'Built OpenAI prompt chain for multi-platform scripts',
      'Integrated Heygen API for avatar video rendering',
      'Built auto-captioning step with Whisper API',
      'Created resize pipeline for 4 platform formats',
      'Set up Notion content calendar with status tracking',
    ],
  },
  {
    id: 'sheet-to-doc',
    icon: '📄',
    tag: 'Google Workspace',
    title: 'Sheet → Document Automation',
    subtitle: 'Proposals in 30 seconds instead of 2 hours — powered by Google Apps Script',
    desc: 'Auto-populate proposal and report templates from Google Sheets — proposals ready in 30 seconds instead of 2 hours.',
    result: 'Zero manual formatting',
    tools: ['Apps Script', 'Google Docs', 'Notion'],
    color: '#5aabff',
    image: null,
    client: 'Consulting Agency',
    duration: '10 days',
    challenge: `A boutique consulting agency produced 15–20 client proposals and monthly reports per month. Each document required manually copying data from their tracking spreadsheet into a Word template, formatting tables, adjusting styling, and exporting to PDF. Two team members were spending 2+ hours per document and the quality varied depending on who prepared it.`,
    solution: `We built a Google Apps Script automation triggered by a button in the master Google Sheet. The script reads client data, selects the correct template based on document type, populates all merge fields, auto-generates charts from the data, applies brand formatting rules, and exports to PDF — all in one click. The final PDF is saved to the client's Google Drive folder and a Notion record is created with a link.`,
    outcome: `Document generation time dropped from 2 hours to under 30 seconds. Quality is now 100% consistent regardless of who initiates the process. The team recovered 40+ hours per month and client feedback on proposal quality improved significantly.`,
    metrics: [
      { label: 'Generation Time', value: '2hr→30sec' },
      { label: 'Docs/Month', value: '20+' },
      { label: 'Hours Recovered', value: '40+/month' },
      { label: 'Consistency', value: '100%' },
    ],
    process: [
      'Audited existing proposal and report templates',
      'Redesigned Google Doc templates with merge field markers',
      'Built Apps Script with template selection logic',
      'Added dynamic chart generation from Sheet data',
      'Created PDF export and Google Drive filing logic',
      'Integrated Notion record creation on completion',
    ],
  },
  {
    id: 'invoice-system',
    icon: '🧾',
    tag: 'Business Automation',
    title: 'Automated Invoice System',
    subtitle: 'Instant professional invoices — triggered by bookings, zero manual work',
    desc: 'Auto-generate and send professional invoices triggered by booking forms, calendar events, or spreadsheet entries.',
    result: 'Instant invoicing',
    tools: ['Make', 'Stripe', 'Google Sheets'],
    color: '#2d8ef5',
    image: null,
    client: 'Freelance Agency',
    duration: '1 week',
    challenge: `A freelance agency was manually creating and sending invoices after every project completion. The process involved logging into Stripe, entering client details, adding line items, setting the amount, and emailing the invoice — taking 15–30 minutes per invoice. With 20–30 invoices per month, this was consuming significant billable time and invoices were sometimes delayed by days.`,
    solution: `We built a Make scenario that listens to a Google Sheet where project completions are logged. When a row is marked "Completed," the automation: looks up client details from the CRM, calculates the invoice total based on rate and hours, creates a Stripe invoice with line items, sends it to the client, logs the invoice ID and status back to the Sheet, and sends a Slack notification to the account manager.`,
    outcome: `Invoices now go out instantly the moment a project is marked complete. Average payment time improved because invoices arrive faster. The agency eliminated 6–8 hours of monthly admin work and late/missed invoices dropped to zero.`,
    metrics: [
      { label: 'Invoice Time', value: '30min→0' },
      { label: 'Invoices/Month', value: '25+' },
      { label: 'Admin Hours Saved', value: '8/month' },
      { label: 'Late Invoices', value: '0' },
    ],
    process: [
      'Mapped existing invoicing workflow and pain points',
      'Set up Google Sheet as project completion trigger',
      'Connected Make to Stripe API for invoice creation',
      'Built CRM lookup step for client data',
      'Added Slack notifications for account manager',
      'Tested with live projects before full deployment',
    ],
  },
  {
    id: 'kpi-dashboard',
    icon: '📊',
    tag: 'Reporting',
    title: 'Weekly KPI Dashboard',
    subtitle: 'Full business visibility delivered every Monday morning — zero effort required',
    desc: 'Automated weekly KPI reports compiled from 5 data sources and delivered to Notion and Slack every Monday at 8am.',
    result: 'Full visibility, zero effort',
    tools: ['n8n', 'Notion', 'Slack'],
    color: '#5aabff',
    image: null,
    client: 'Growing SaaS',
    duration: '2 weeks',
    challenge: `The leadership team of a growing SaaS company needed weekly insight into 8 core KPIs pulled from Stripe (revenue), HubSpot (leads), Google Analytics (traffic), Jira (sprint velocity), and their own database (churn/retention). Preparing the weekly report manually took their ops manager 3–4 hours every Monday morning and was often inconsistent in format.`,
    solution: `We built an n8n workflow scheduled for 7am every Monday that: pulls data from all 5 sources via their APIs, calculates week-over-week and month-to-date comparisons, generates trend indicators, populates a Notion dashboard template with live data, posts a formatted summary to the #leadership Slack channel with key highlights and any metrics that changed more than 10%.`,
    outcome: `The ops manager's 3–4 hour Monday task is now fully automated. Leadership has the full picture waiting in Slack and Notion by the time they start their week. Decision-making speed improved and the team caught a churn spike 3 weeks earlier than they would have with the old process.`,
    metrics: [
      { label: 'Report Time', value: '4hr→0' },
      { label: 'Data Sources', value: '5 APIs' },
      { label: 'KPIs Tracked', value: '8 metrics' },
      { label: 'Delivery', value: 'Every Monday 8am' },
    ],
    process: [
      'Mapped all 5 data sources and their APIs',
      'Designed Notion dashboard template with calculated fields',
      'Built n8n workflow with parallel data fetch branches',
      'Added week-over-week comparison logic',
      'Designed Slack message format with emoji trend indicators',
      'Set up alerting for metrics outside normal thresholds',
    ],
  },
]

// ── Services Data ──────────────────────────────────────────────────────────
export const SERVICES_DATA = [
  {
    id: 'notion-workspace',
    icon: '◈',
    title: 'Notion Workspaces',
    tagline: 'Your entire business, beautifully organized in Notion',
    desc: 'Custom-built Notion databases, dashboards, and wikis tailored to your team\'s exact workflow.',
    long: 'We design and build Notion workspaces from scratch — or restructure your existing one. Every database, relation, and view is intentional. We build company wikis, CRMs, project management systems, HR databases, content calendars, and more.',
    features: ['Custom database architecture', 'Linked databases & relations', 'Filtered views per team role', 'Automated status updates', 'Template systems', 'Team onboarding docs'],
    color: '#2d8ef5',
    tools: ['Notion', 'Notion API'],
  },
  {
    id: 'workflow-automation',
    icon: '⟳',
    title: 'Workflow Automation',
    tagline: 'Repetitive tasks eliminated. Permanent.',
    desc: 'End-to-end automation using n8n, Make, and Zapier — connecting your tools to work seamlessly together.',
    long: 'We map your manual workflows and replace them with automated pipelines. From simple triggers to complex multi-step sequences with conditionals, error handling, and retries. If you do it more than once a week, we can automate it.',
    features: ['Trigger-based automations', 'Multi-step workflows', 'Conditional logic', 'Error handling & retries', 'Slack/email notifications', 'Monitoring dashboards'],
    color: '#5aabff',
    tools: ['n8n', 'Make', 'Zapier'],
  },
  {
    id: 'ai-integrations',
    icon: '⬡',
    title: 'AI Integrations',
    tagline: 'GPT-powered logic embedded into your actual business',
    desc: 'Embed GPT-powered logic and AI workflows directly into your Notion workspace and business processes.',
    long: 'We integrate AI into your existing systems — not as a separate tool, but woven into your actual workflows. AI that summarizes meetings, classifies leads, writes first-draft content, answers support queries from your knowledge base, and flags anomalies in your data.',
    features: ['GPT-4 integrations', 'Document summarization', 'Lead scoring & classification', 'AI content generation', 'Smart email drafts', 'Knowledge base Q&A'],
    color: '#2d8ef5',
    tools: ['OpenAI', 'n8n', 'Notion'],
  },
  {
    id: 'google-workspace',
    icon: '⌘',
    title: 'Google Workspace',
    tagline: 'Sheets, Docs, Gmail, Drive — automated and connected',
    desc: 'Automate Sheets, Docs, Gmail, Drive, and Calendar — connected to your core operational systems.',
    long: 'Google Workspace is powerful but most teams use 10% of what\'s possible. We automate report generation from Sheets, document creation from templates, Gmail workflows, Drive organization, and Calendar-triggered actions — all connected to your Notion and automation stack.',
    features: ['Sheets → Doc generation', 'Gmail automation', 'Drive auto-organization', 'Calendar triggers', 'Google Forms → Notion', 'Apps Script development'],
    color: '#5aabff',
    tools: ['Google Sheets', 'Apps Script', 'Gmail API'],
  },
  {
    id: 'api-connections',
    icon: '✦',
    title: 'API Connections',
    tagline: 'Any tool. Any platform. We build the bridge.',
    desc: 'Bridge any tool to any platform with robust, production-grade API integrations and webhooks.',
    long: 'Have a custom app, niche SaaS tool, or internal system that doesn\'t have native integrations? We build custom API connections, webhooks, and middleware that make your unique stack talk to each other — reliably and at scale.',
    features: ['REST & GraphQL APIs', 'Webhook configuration', 'Custom middleware', 'Rate limit handling', 'Auth & token management', 'API documentation'],
    color: '#2d8ef5',
    tools: ['REST APIs', 'Webhooks', 'Node.js'],
  },
  {
    id: 'system-design',
    icon: '◉',
    title: 'System Design',
    tagline: 'Architecture that scales — built right from the start',
    desc: 'Architecture consulting to design scalable operational systems that grow and adapt with your business.',
    long: 'Before writing a single automation, we help you design the right system architecture. We map your tools, data flows, team roles, and growth plans — then design an operations stack that won\'t need to be rebuilt every 6 months.',
    features: ['Operations audit', 'Tool stack optimization', 'Data flow mapping', 'Scalability planning', 'Team workflow design', 'Documentation framework'],
    color: '#5aabff',
    tools: ['Miro', 'Notion', 'Loom'],
  },
]
